-- PawCore Systems Cortex Analyst Services Setup
-- This script creates Cortex Analyst services for structured data analysis

USE ROLE SNOWFLAKE_INTELLIGENCE_ADMIN_RL;
USE DATABASE PAWCORE_INTELLIGENCE_DEMO;
USE SCHEMA BUSINESS_DATA;

-- Create Cortex Analyst Service for Sales Performance
CREATE OR REPLACE CORTEX ANALYST SERVICE Analyst_PawCore Systems_Sales_Performance
ON PAWCORE_SALES_SEMANTIC_VIEW
WAREHOUSE = PAWCORE_INTELLIGENCE_WH
AS (
    SELECT 
        DATE,
        REGION_NAME,
        PRODUCT_NAME,
        ACTUAL_SALES,
        FORECAST_SALES,
        VARIANCE,
        PCT_OF_FORECAST,
        INVENTORY_UNITS_AVAILABLE,
        MARKETING_ENGAGEMENT_SCORE
    FROM PAWCORE_SALES_SEMANTIC_VIEW
);

-- Create Cortex Analyst Service for Financial Analysis
CREATE OR REPLACE CORTEX ANALYST SERVICE Analyst_PawCore Systems_Financial_Data
ON PAWCORE_SALES_SEMANTIC_VIEW
WAREHOUSE = PAWCORE_INTELLIGENCE_WH
AS (
    SELECT 
        DATE,
        REGION_NAME,
        PRODUCT_NAME,
        ACTUAL_SALES,
        FORECAST_SALES,
        VARIANCE,
        PCT_OF_FORECAST,
        PRODUCT_PRICE,
        PRODUCT_COST,
        (ACTUAL_SALES - PRODUCT_COST) as GROSS_PROFIT,
        ((ACTUAL_SALES - PRODUCT_COST) / ACTUAL_SALES * 100) as GROSS_MARGIN_PCT
    FROM PAWCORE_SALES_SEMANTIC_VIEW
    JOIN PRODUCT_DIM ON PAWCORE_SALES_SEMANTIC_VIEW.PRODUCT_NAME = PRODUCT_DIM.PRODUCT_NAME
);

-- Create Cortex Analyst Service for Marketing Performance
CREATE OR REPLACE CORTEX ANALYST SERVICE Analyst_PawCore Systems_Marketing_Metrics
ON PAWCORE_SALES_SEMANTIC_VIEW
WAREHOUSE = PAWCORE_INTELLIGENCE_WH
AS (
    SELECT 
        DATE,
        REGION_NAME,
        PRODUCT_NAME,
        ACTUAL_SALES,
        FORECAST_SALES,
        MARKETING_ENGAGEMENT_SCORE,
        INVENTORY_UNITS_AVAILABLE,
        CASE 
            WHEN MARKETING_ENGAGEMENT_SCORE > 200 THEN 'High Engagement'
            WHEN MARKETING_ENGAGEMENT_SCORE > 100 THEN 'Medium Engagement'
            ELSE 'Low Engagement'
        END as ENGAGEMENT_LEVEL,
        (ACTUAL_SALES / NULLIF(MARKETING_ENGAGEMENT_SCORE, 0)) as SALES_PER_ENGAGEMENT_POINT
    FROM PAWCORE_SALES_SEMANTIC_VIEW
);

-- Create Cortex Analyst Service for Regional Performance
CREATE OR REPLACE CORTEX ANALYST SERVICE Analyst_PawCore Systems_Regional_Analysis
ON PAWCORE_SALES_SEMANTIC_VIEW
WAREHOUSE = PAWCORE_INTELLIGENCE_WH
AS (
    SELECT 
        DATE,
        REGION_NAME,
        CONTINENT,
        PRODUCT_NAME,
        ACTUAL_SALES,
        FORECAST_SALES,
        VARIANCE,
        PCT_OF_FORECAST,
        INVENTORY_UNITS_AVAILABLE,
        MARKETING_ENGAGEMENT_SCORE,
        CASE 
            WHEN PCT_OF_FORECAST >= 100 THEN 'Exceeded Forecast'
            WHEN PCT_OF_FORECAST >= 90 THEN 'Near Forecast'
            ELSE 'Below Forecast'
        END as FORECAST_PERFORMANCE
    FROM PAWCORE_SALES_SEMANTIC_VIEW
    JOIN REGION_DIM ON PAWCORE_SALES_SEMANTIC_VIEW.REGION_NAME = REGION_DIM.REGION_NAME
);

-- Create Cortex Analyst Service for Product Performance
CREATE OR REPLACE CORTEX ANALYST SERVICE Analyst_PawCore Systems_Product_Analysis
ON PAWCORE_SALES_SEMANTIC_VIEW
WAREHOUSE = PAWCORE_INTELLIGENCE_WH
AS (
    SELECT 
        DATE,
        PRODUCT_NAME,
        PRODUCT_CATEGORY,
        PRODUCT_PRICE,
        REGION_NAME,
        ACTUAL_SALES,
        FORECAST_SALES,
        VARIANCE,
        PCT_OF_FORECAST,
        INVENTORY_UNITS_AVAILABLE,
        MARKETING_ENGAGEMENT_SCORE,
        (ACTUAL_SALES / PRODUCT_PRICE) as UNITS_SOLD,
        CASE 
            WHEN PRODUCT_CATEGORY = 'GPS Tracking' THEN 'Location Services'
            WHEN PRODUCT_CATEGORY = 'Health Monitoring' THEN 'Health Services'
            WHEN PRODUCT_CATEGORY = 'Training' THEN 'Behavior Services'
            ELSE 'Other'
        END as SERVICE_CATEGORY
    FROM PAWCORE_SALES_SEMANTIC_VIEW
    JOIN PRODUCT_DIM ON PAWCORE_SALES_SEMANTIC_VIEW.PRODUCT_NAME = PRODUCT_DIM.PRODUCT_NAME
);

-- Grant permissions for Cortex Analyst services
GRANT USAGE ON CORTEX ANALYST SERVICE Analyst_PawCore Systems_Sales_Performance TO ROLE PAWCORE_WEBINAR_ROLE;
GRANT USAGE ON CORTEX ANALYST SERVICE Analyst_PawCore Systems_Financial_Data TO ROLE PAWCORE_WEBINAR_ROLE;
GRANT USAGE ON CORTEX ANALYST SERVICE Analyst_PawCore Systems_Marketing_Metrics TO ROLE PAWCORE_WEBINAR_ROLE;
GRANT USAGE ON CORTEX ANALYST SERVICE Analyst_PawCore Systems_Regional_Analysis TO ROLE PAWCORE_WEBINAR_ROLE;
GRANT USAGE ON CORTEX ANALYST SERVICE Analyst_PawCore Systems_Product_Analysis TO ROLE PAWCORE_WEBINAR_ROLE;

-- Verification queries
SELECT 
    'Sales Performance Analyst Service' as service_name,
    ANALYST_SERVICE_NAME,
    STATUS
FROM PAWCORE_INTELLIGENCE_DEMO.INFORMATION_SCHEMA.CORTEX_ANALYST_SERVICES 
WHERE ANALYST_SERVICE_NAME = 'Analyst_PawCore Systems_Sales_Performance';

SELECT 
    'Financial Data Analyst Service' as service_name,
    ANALYST_SERVICE_NAME,
    STATUS
FROM PAWCORE_INTELLIGENCE_DEMO.INFORMATION_SCHEMA.CORTEX_ANALYST_SERVICES 
WHERE ANALYST_SERVICE_NAME = 'Analyst_PawCore Systems_Financial_Data';

SELECT 
    'Marketing Metrics Analyst Service' as service_name,
    ANALYST_SERVICE_NAME,
    STATUS
FROM PAWCORE_INTELLIGENCE_DEMO.INFORMATION_SCHEMA.CORTEX_ANALYST_SERVICES 
WHERE ANALYST_SERVICE_NAME = 'Analyst_PawCore Systems_Marketing_Metrics';

SELECT 
    'Regional Analysis Analyst Service' as service_name,
    ANALYST_SERVICE_NAME,
    STATUS
FROM PAWCORE_INTELLIGENCE_DEMO.INFORMATION_SCHEMA.CORTEX_ANALYST_SERVICES 
WHERE ANALYST_SERVICE_NAME = 'Analyst_PawCore Systems_Regional_Analysis';

SELECT 
    'Product Analysis Analyst Service' as service_name,
    ANALYST_SERVICE_NAME,
    STATUS
FROM PAWCORE_INTELLIGENCE_DEMO.INFORMATION_SCHEMA.CORTEX_ANALYST_SERVICES 
WHERE ANALYST_SERVICE_NAME = 'Analyst_PawCore Systems_Product_Analysis'; 