-- Fix Document Stage - CORRECTED VERSION
-- Based on your screenshot, the stage is likely in BUSINESS_DATA schema

USE ROLE ACCOUNTADMIN;
USE DATABASE PAWCORE_INTELLIGENCE_DEMO;
USE SCHEMA BUSINESS_DATA;  -- Changed from DOCUMENTS to BUSINESS_DATA
USE WAREHOUSE PAWCORE_INTELLIGENCE_WH;

-- Step 1: Check if DOCUMENT_STAGE already exists in BUSINESS_DATA
SHOW STAGES;

-- Step 2: If it doesn't exist, create it
CREATE OR REPLACE STAGE DOCUMENT_STAGE;

-- Step 3: List files in the stage (after you upload them)
SELECT * FROM DIRECTORY(@DOCUMENT_STAGE);

-- Step 4: Create tables for unstructured data in BUSINESS_DATA schema
CREATE OR REPLACE TABLE SLACK_MESSAGES (
    MESSAGE_ID STRING,
    CHANNEL STRING,
    AUTHOR STRING,
    MESSAGE_TEXT STRING,
    TIMESTAMP TIMESTAMP,
    SENTIMENT STRING
);

CREATE OR REPLACE TABLE CUSTOMER_REVIEWS (
    REVIEW_ID STRING,
    DATE DATE,
    PRODUCT STRING,
    CUSTOMER_NAME STRING,
    RATING INTEGER,
    REVIEW_TEXT STRING,
    SENTIMENT STRING,
    REVIEW_CATEGORY STRING,
    VERIFIED_PURCHASE STRING,
    HELPFUL_VOTES INTEGER,
    REVIEW_LENGTH INTEGER,
    REGION STRING,
    CUSTOMER_SEGMENT STRING
);

-- Step 5: Load CSV data (only CSV files, not markdown)
-- Load Slack messages
COPY INTO SLACK_MESSAGES
FROM @DOCUMENT_STAGE/pawcore_slack.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load customer reviews
COPY INTO CUSTOMER_REVIEWS
FROM @DOCUMENT_STAGE/customer_reviews.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Step 6: Create transcript table
CREATE OR REPLACE TABLE CALL_TRANSCRIPT (
    SEGMENT_ID STRING,
    SPEAKER STRING,
    TEXT STRING,
    TIMESTAMP TIMESTAMP,
    SENTIMENT STRING
);

-- Step 7: Verify data loading
SELECT 'SLACK_MESSAGES' as table_name, COUNT(*) as row_count FROM SLACK_MESSAGES
UNION ALL
SELECT 'CUSTOMER_REVIEWS', COUNT(*) FROM CUSTOMER_REVIEWS
UNION ALL
SELECT 'CALL_TRANSCRIPT', COUNT(*) FROM CALL_TRANSCRIPT
ORDER BY table_name;

-- Note: The markdown files (Quarterly_Sales_Speech_PawCore.md, etc.) 
-- should be processed through Document AI in the UI, not loaded via SQL
