-- Fixed Setup SQL for PawCore Hands-On Lab
-- Use this corrected version

USE ROLE ACCOUNTADMIN;

-- Create file formats
CREATE OR REPLACE FILE FORMAT CSV_FORMAT 
    TYPE = CSV 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    SKIP_HEADER = 1;

-- For binary files, don't specify TYPE - let Snowflake auto-detect
CREATE OR REPLACE FILE FORMAT BINARY_FORMAT;

-- Create stages
CREATE OR REPLACE STAGE INTERNAL_DATA_STAGE 
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE STAGE DOCUMENT_STAGE;

CREATE OR REPLACE STAGE IMAGE_STAGE;

CREATE OR REPLACE STAGE AUDIO_STAGE;

-- Alternative: If you want to be more specific about file types
-- CREATE OR REPLACE FILE FORMAT PDF_FORMAT TYPE = PDF;
-- CREATE OR REPLACE FILE FORMAT IMAGE_FORMAT TYPE = IMAGE;
-- CREATE OR REPLACE FILE FORMAT AUDIO_FORMAT TYPE = AUDIO;

-- Then use these specific formats:
-- CREATE OR REPLACE STAGE IMAGE_STAGE FILE_FORMAT = IMAGE_FORMAT;
-- CREATE OR REPLACE STAGE AUDIO_STAGE FILE_FORMAT = AUDIO_FORMAT;
